"""Gate a trained Product head on fixed, public Classic states before paired PPO.

The view set is generated by deterministic legal full moves. Both actors see
only their own wire observation; no hidden state or hosted replay is an input.
"""

import argparse
import hashlib
import json
from pathlib import Path

import numpy as np

from integrations.classic_contract import ENGINE_SHA256
from integrations.softmax.engine import Match
from integrations.softmax.neural_codec import encode_wire_observation
from integrations.softmax.protocol import PASS
from integrations.spatial_policy_bundle import SpatialPlayerPolicy

SEEDS = (10943771, 10943777, 10943789, 10943797, 10943803, 10943809, 10943821, 10943833)
TURNS = (0, 25, 50, 100, 150)
MIN_LEGAL_EFFECT = 1e-3
VIEWS_SHA256 = "f5d6cc004ae2d9f615585d8197b2b6a13b25d391c19a197c3c1b20b5b6c8d897"


def sha(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def choose_public_move(observation, legal, rng):
    """Prefer expansion with a large source stack, using the public wire only."""
    full = np.flatnonzero(legal[:1764])
    if not len(full):
        return PASS.copy()
    grid = np.asarray(observation["owner_grid"])
    armies = np.asarray(observation["army_grid"])
    height, width = grid.shape
    direction, cell = np.divmod(full, 441)
    row, col = np.divmod(cell, 21)
    dest_row = row + np.take((-1, 1, 0, 0), direction)
    dest_col = col + np.take((0, 0, -1, 1), direction)
    inside = (dest_row >= 0) & (dest_row < height) & (dest_col >= 0) & (dest_col < width)
    neutral = np.zeros(len(full), dtype=bool)
    neutral[inside] = grid[dest_row[inside], dest_col[inside]] == 0
    # A fixed seed breaks ties while keeping the trajectory independent of the
    # Product checkpoint being evaluated.
    score = armies[row, col] + 6 * neutral + rng.uniform(0, 3, len(full))
    index = int(full[int(np.argmax(score))])
    direction, cell = divmod(index, 441)
    row, col = divmod(cell, 21)
    return [0, row, col, direction, 0]


def make_views(output):
    values, masks, labels, land = [], [], [], []
    for seed in SEEDS:
        match = Match(seed)
        rng = np.random.default_rng(seed ^ 0x5A1731)
        for turn in range(max(TURNS) + 1):
            observations = [match.observation(seat) for seat in (0, 1)]
            encoded = [encode_wire_observation(obs) for obs in observations]
            if turn in TURNS:
                for seat, ((value, mask), obs) in enumerate(zip(encoded, observations, strict=True)):
                    values.append(value)
                    masks.append(mask)
                    labels.append((seed, turn, seat))
                    land.append(obs["my_land"])
            if turn == max(TURNS):
                break
            actions = [choose_public_move(obs, encoded[seat][1], rng)
                       for seat, obs in enumerate(observations)]
            if match.advance(actions) >= 0:
                raise ValueError(f"Fixed public trajectory ended before turn {max(TURNS)}: {seed}")
    values = np.asarray(values, dtype=np.float32)
    masks = np.asarray(masks, dtype=bool)
    labels = np.asarray(labels, dtype=np.int64)
    land = np.asarray(land, dtype=np.int32)
    if (values.shape != (len(SEEDS) * len(TURNS) * 2, 7056)
            or masks.shape != (len(values), 3529) or not masks.any(axis=1).all()
            or np.any(masks.sum(axis=1) < 1) or np.sum(masks.sum(axis=1) > 1) < 16 or np.max(land) <= 1):
        raise ValueError(f"Fixed Classic views lack legal expanded states: {values.shape=} {masks.shape=} "
                         f"{masks.sum(axis=1).min()=} {land.max()=}")
    output.parent.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(output, values=values, masks=masks, labels=labels, land=land)
    if sha(output) != VIEWS_SHA256:
        raise ValueError("Fixed public Classic view bytes changed")
    receipt = dict(schema="generals-product-public-activation-views-v1", engine_sha256=ENGINE_SHA256,
                   seeds=SEEDS, turns=TURNS, public_states=len(values), expanded_states=int(np.sum(land > 1)),
                   views_sha256=sha(output))
    output.with_suffix(".json").write_text(json.dumps(receipt, indent=2) + "\n")
    return receipt


def audit(source_bundle, trained_bundle, checkpoint, parity_report, views):
    manifest = json.loads(views.with_suffix(".json").read_text())
    if (manifest["schema"] != "generals-product-public-activation-views-v1"
            or manifest["engine_sha256"] != ENGINE_SHA256 or tuple(manifest["seeds"]) != SEEDS
            or tuple(manifest["turns"]) != TURNS or manifest["views_sha256"] != VIEWS_SHA256
            or sha(views) != VIEWS_SHA256):
        raise ValueError("Fixed public Classic view identity differs")
    with np.load(views, allow_pickle=False) as data:
        values, masks = data["values"], data["masks"]
        labels, land = data["labels"], data["land"]
    if (values.shape != (len(SEEDS) * len(TURNS) * 2, 7056)
            or masks.shape != (len(values), 3529) or labels.shape != (len(values), 3)
            or not np.array_equal(labels, np.asarray([(seed, turn, seat) for seed in SEEDS
                for turn in TURNS for seat in (0, 1)], dtype=np.int64))
            or np.any(masks.sum(axis=1) < 1) or np.sum(masks.sum(axis=1) > 1) < 16
            or int(np.sum(land > 1)) != manifest["expanded_states"]
            or not np.isfinite(values).all()):
        raise ValueError("Fixed public Classic view contents differ")
    source = SpatialPlayerPolicy(source_bundle)
    trained = SpatialPlayerPolicy(trained_bundle)
    checkpoint_sha = sha(checkpoint)
    trained_manifest_sha = sha(trained_bundle / "spatial-policy.json")
    if (source.asset.metadata["abi_sha256"] != trained.asset.metadata["abi_sha256"]
            or source.asset.metadata["factory_source_sha256"] != trained.asset.metadata["factory_source_sha256"]
            or source.asset.metadata["sampler"] != trained.asset.metadata["sampler"]
            or sha(source_bundle / "policy.bin") != source.asset.metadata["policy_sha256"]
            or sha(trained_bundle / "policy.bin") != checkpoint_sha
            or checkpoint_sha != trained.asset.metadata["policy_sha256"]):
        raise ValueError("Source/trained Product asset or sampler identity differs")
    q0 = source.weights["product_action_kernel"]
    if not np.array_equal(q0, np.zeros_like(q0)):
        raise ValueError("Product source head was not exactly zero")
    parity = json.loads(parity_report.read_text())
    if (parity.get("checkpoint_sha256") != checkpoint_sha
            or parity.get("factory_source_sha256") != trained.asset.metadata["factory_source_sha256"]
            or parity.get("bundle_manifest_sha256") != trained_manifest_sha
            or parity.get("engine_sha256") != ENGINE_SHA256
            or parity.get("public_states", 0) < 16
            or parity.get("matching_top_actions") != parity.get("public_states")
            or parity.get("max_logit_difference", 1) > 2e-5
            or parity.get("max_action_probability_difference", 1) > 1e-5):
        raise ValueError("Native-to-serving Product parity proof is missing or mismatched")
    raw = trained.forward(values)
    zero_weights = dict(trained.weights, product_action_kernel=np.zeros_like(trained.weights["product_action_kernel"]))
    zero = trained._forward(values, np, zero_weights)
    if not np.isfinite(zero).all() or raw.shape != (len(values), 3530):
        raise ValueError("Product activation outputs are invalid")
    legal_delta = (raw[:, :3529] - zero[:, :3529])[masks]
    maximum = float(np.max(np.abs(legal_delta)))
    rms = float(np.sqrt(np.mean(np.square(legal_delta.astype(np.float64)))))
    movement = {}
    for key in ("product_local_kernel", "product_global_kernel", "product_action_kernel"):
        delta = trained.weights[key].astype(np.float64) - source.weights[key].astype(np.float64)
        movement[key] = dict(l2=float(np.linalg.norm(delta)), max_abs=float(np.max(np.abs(delta))),
                             changed_words=int(np.count_nonzero(delta)))
    result = dict(schema="generals-product-activation-gate-v1", passed=False,
                  source_policy_sha256=source.asset.metadata["policy_sha256"],
                  trained_checkpoint_sha256=checkpoint_sha, trained_bundle_manifest_sha256=trained_manifest_sha,
                  native_serving_parity_sha256=sha(parity_report), views_sha256=sha(views),
                  public_states=len(values), expanded_states=int(np.sum(land > 1)),
                  legal_logit_delta_rms=rms, legal_logit_delta_max_abs=maximum,
                  q_u_v_movement=movement, min_legal_logit_delta_max_abs=MIN_LEGAL_EFFECT)
    result["passed"] = bool(maximum > MIN_LEGAL_EFFECT and all(item["changed_words"] > 0 for item in movement.values()))
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)
    make = sub.add_parser("make-views")
    make.add_argument("--output", required=True, type=Path)
    gate = sub.add_parser("gate")
    gate.add_argument("--source-bundle", required=True, type=Path)
    gate.add_argument("--trained-bundle", required=True, type=Path)
    gate.add_argument("--checkpoint", required=True, type=Path)
    gate.add_argument("--parity-report", required=True, type=Path)
    gate.add_argument("--views", required=True, type=Path)
    gate.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()
    if args.command == "make-views":
        result = make_views(args.output)
    else:
        result = audit(args.source_bundle, args.trained_bundle, args.checkpoint, args.parity_report, args.views)
        args.output.write_text(json.dumps(result, indent=2) + "\n")
        if not result["passed"]:
            raise SystemExit("Product activation gate failed: " + json.dumps(result))
    print(json.dumps(result), flush=True)


if __name__ == "__main__":
    main()
